"""initial schema

Revision ID: 07f07de8bcbe
Revises: 
Create Date: 2026-09-13 02:12:06.662098
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '07f07de8bcbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('segment', sa.String(length=80), nullable=False),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('fit_preference', sa.String(length=16), nullable=False),
    sa.Column('photo_consent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_keys',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_keys_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_keys_key'), ['key'], unique=True)

    op.create_table('photo_analyses',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('shoulder_hip_ratio', sa.Float(), nullable=True),
    sa.Column('waist_hip_ratio', sa.Float(), nullable=True),
    sa.Column('torso_leg_ratio', sa.Float(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photo_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_photo_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('products',
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('audience', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=400), nullable=False),
    sa.Column('color', sa.String(length=40), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('modeling', sa.String(length=24), nullable=False),
    sa.Column('fabric', sa.String(length=120), nullable=False),
    sa.Column('composition', sa.String(length=200), nullable=False),
    sa.Column('elasticity_pct', sa.Float(), nullable=False),
    sa.Column('care', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_company_id'), ['company_id'], unique=False)

    op.create_table('user_measurements',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hip', sa.Float(), nullable=True),
    sa.Column('shoulder', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_measurements_user_id'), ['user_id'], unique=False)

    op.create_table('sku_sizes',
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('size_label', sa.String(length=12), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'size_label', name='uq_product_size')
    )
    with op.batch_alter_table('sku_sizes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sku_sizes_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sku_sizes_sku'), ['sku'], unique=True)

    op.create_table('fit_analyses',
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('evaluated_sku_id', sa.String(length=32), nullable=False),
    sa.Column('recommended_sku_id', sa.String(length=32), nullable=False),
    sa.Column('photo_analysis_id', sa.String(length=32), nullable=True),
    sa.Column('evaluated_size', sa.String(length=12), nullable=False),
    sa.Column('recommended_size', sa.String(length=12), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=12), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('fit_preference', sa.String(length=16), nullable=False),
    sa.Column('regional_analysis', sa.JSON(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('comparison', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['evaluated_sku_id'], ['sku_sizes.id'], ),
    sa.ForeignKeyConstraint(['photo_analysis_id'], ['photo_analyses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recommended_sku_id'], ['sku_sizes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fit_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fit_analyses_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fit_analyses_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fit_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('garment_measurements',
    sa.Column('sku_size_id', sa.String(length=32), nullable=False),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hip', sa.Float(), nullable=True),
    sa.Column('shoulder', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('sleeve', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sku_size_id'], ['sku_sizes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku_size_id')
    )
    op.create_table('feedbacks',
    sa.Column('fit_analysis_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('purchased_size', sa.String(length=12), nullable=True),
    sa.Column('fit_rating', sa.String(length=16), nullable=False),
    sa.Column('followed_recommendation', sa.Boolean(), nullable=False),
    sa.Column('returned', sa.Boolean(), nullable=False),
    sa.Column('return_reason', sa.String(length=120), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fit_analysis_id'], ['fit_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_fit_analysis_id'), ['fit_analysis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_fit_analysis_id'))

    op.drop_table('feedbacks')
    op.drop_table('garment_measurements')
    with op.batch_alter_table('fit_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fit_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_fit_analyses_product_id'))
        batch_op.drop_index(batch_op.f('ix_fit_analyses_company_id'))

    op.drop_table('fit_analyses')
    with op.batch_alter_table('sku_sizes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sku_sizes_sku'))
        batch_op.drop_index(batch_op.f('ix_sku_sizes_product_id'))

    op.drop_table('sku_sizes')
    with op.batch_alter_table('user_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_measurements_user_id'))

    op.drop_table('user_measurements')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_company_id'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('photo_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_photo_analyses_user_id'))

    op.drop_table('photo_analyses')
    with op.batch_alter_table('integration_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_keys_key'))
        batch_op.drop_index(batch_op.f('ix_integration_keys_company_id'))

    op.drop_table('integration_keys')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
